kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zookeeper
  namespace: sanayak-pinot
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Standard_LRS
  kind: managed